### ISSUE TITLE
decorator autocompletion

### ISSUE THREAD

**Issue by Northys** [juzna/intellij-neon#39]
Plugin does not suggest classes and interfaces while there is no dash.

```yaml
decorator:
  - Works:
    setup:
      - bb(%option%)
```

```yaml
decorator:
  DoesNotWork:
    setup:
      - bb(%option%)
```
<img width="381" alt="screen shot 2016-05-02 at 14 22 47" src="https://cloud.githubusercontent.com/assets/2878126/14954375/30fcb396-1072-11e6-9a6a-a3b30aaf30dc.png">
<img width="209" alt="screen shot 2016-05-02 at 14 29 18" src="https://cloud.githubusercontent.com/assets/2878126/14954390/4a24e1fe-1072-11e6-9091-7fb34b8fd4a9.png">
