### ISSUE TITLE
Auto-reorder entries according to keys

### ISSUE THREAD

**Issue by vasek-b** [juzna/intellij-neon#50]
I'd like to have an option to trigger reordering of all entries in a file by keys' names.

Basically to turn something like this
```
second:
    third: 'something'
    fourth: 'something else'
first: 'my name'
```
into that
```
first: 'my name'
second:
    fourth: 'something else'
    third: 'something'
```

It would help with keeping my translation files organized.
